apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-api
  template:
    metadata:
      labels:
        app: client-api
    spec:
      containers:
      - name: client-api
        image: client:0.0.5
        imagePullPolicy: "IfNotPresent"
        command: ['sh', '-c']
        args: ['GRPC_VERBOSITY=DEBUG GRPC_TRACE=all  node dist/main.js']
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
          name: http
        env:
          - name: GRPC_DNS
            value: ms-api.default.svc.cluster.local:5000