apiVersion: v1
kind: Service
metadata:
  name: ms-api
  namespace: default
  labels:
    app: ms-api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3000
      targetPort: http
      name: http
    - port: 5000
      protocol: TCP
      targetPort: grpc
      name: grpc
  selector:
    app: ms-api
  
